//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public int Grup_Id { get; set; }
        public string Grup_Nom { get; set; }
        public int Jor_Id { get; set; }
        public int Hor_Id { get; set; }
        public int Sec_Id { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual jornada jornada { get; set; }
        public virtual sectores sectores { get; set; }
    }
}
