//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_laboral
    {
        public int Hl_Id { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public Nullable<int> Ds_Id { get; set; }
        public string Hl_Inicio { get; set; }
        public string Hl_Termino { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual diassemanales diassemanales { get; set; }
    }
}
